/* tslint:disable */
/* eslint-disable */
/**
 * Inquiro API
 * AI-powered research discovery backend for Inquiro.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { HTTPValidationError } from '../models';
// @ts-ignore
import type { PaperSummaryRequest } from '../models';
// @ts-ignore
import type { PaperSummaryResponse } from '../models';
/**
 * PaperApi - axios parameter creator
 */
export const PaperApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Stream the PDF file of the specified paper. This URL can be used directly as the source for frontend PDF viewers.
         * @summary Get the PDF of the specified paper
         * @param {number} paperId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPaperPdfPapersPaperIdPdfGet: async (paperId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'paperId' is not null or undefined
            assertParamExists('getPaperPdfPapersPaperIdPdfGet', 'paperId', paperId)
            const localVarPath = `/papers{paper_id}/pdf`
                .replace(`{${"paper_id"}}`, encodeURIComponent(String(paperId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns the summary of the specified paper.
         * @summary Summarise the specified paper
         * @param {number} paperId 
         * @param {PaperSummaryRequest} paperSummaryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        summaryPapersPaperIdSummaryPost: async (paperId: number, paperSummaryRequest: PaperSummaryRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'paperId' is not null or undefined
            assertParamExists('summaryPapersPaperIdSummaryPost', 'paperId', paperId)
            // verify required parameter 'paperSummaryRequest' is not null or undefined
            assertParamExists('summaryPapersPaperIdSummaryPost', 'paperSummaryRequest', paperSummaryRequest)
            const localVarPath = `/papers{paper_id}/summary`
                .replace(`{${"paper_id"}}`, encodeURIComponent(String(paperId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(paperSummaryRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PaperApi - functional programming interface
 */
export const PaperApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PaperApiAxiosParamCreator(configuration)
    return {
        /**
         * Stream the PDF file of the specified paper. This URL can be used directly as the source for frontend PDF viewers.
         * @summary Get the PDF of the specified paper
         * @param {number} paperId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPaperPdfPapersPaperIdPdfGet(paperId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPaperPdfPapersPaperIdPdfGet(paperId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PaperApi.getPaperPdfPapersPaperIdPdfGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns the summary of the specified paper.
         * @summary Summarise the specified paper
         * @param {number} paperId 
         * @param {PaperSummaryRequest} paperSummaryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async summaryPapersPaperIdSummaryPost(paperId: number, paperSummaryRequest: PaperSummaryRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaperSummaryResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.summaryPapersPaperIdSummaryPost(paperId, paperSummaryRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PaperApi.summaryPapersPaperIdSummaryPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PaperApi - factory interface
 */
export const PaperApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PaperApiFp(configuration)
    return {
        /**
         * Stream the PDF file of the specified paper. This URL can be used directly as the source for frontend PDF viewers.
         * @summary Get the PDF of the specified paper
         * @param {number} paperId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPaperPdfPapersPaperIdPdfGet(paperId: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.getPaperPdfPapersPaperIdPdfGet(paperId, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns the summary of the specified paper.
         * @summary Summarise the specified paper
         * @param {number} paperId 
         * @param {PaperSummaryRequest} paperSummaryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        summaryPapersPaperIdSummaryPost(paperId: number, paperSummaryRequest: PaperSummaryRequest, options?: RawAxiosRequestConfig): AxiosPromise<PaperSummaryResponse> {
            return localVarFp.summaryPapersPaperIdSummaryPost(paperId, paperSummaryRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PaperApi - object-oriented interface
 */
export class PaperApi extends BaseAPI {
    /**
     * Stream the PDF file of the specified paper. This URL can be used directly as the source for frontend PDF viewers.
     * @summary Get the PDF of the specified paper
     * @param {number} paperId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getPaperPdfPapersPaperIdPdfGet(paperId: number, options?: RawAxiosRequestConfig) {
        return PaperApiFp(this.configuration).getPaperPdfPapersPaperIdPdfGet(paperId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns the summary of the specified paper.
     * @summary Summarise the specified paper
     * @param {number} paperId 
     * @param {PaperSummaryRequest} paperSummaryRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public summaryPapersPaperIdSummaryPost(paperId: number, paperSummaryRequest: PaperSummaryRequest, options?: RawAxiosRequestConfig) {
        return PaperApiFp(this.configuration).summaryPapersPaperIdSummaryPost(paperId, paperSummaryRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

