/* tslint:disable */
/* eslint-disable */
/**
 * Inquiro API
 * AI-powered research discovery backend for Inquiro.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { HTTPValidationError } from '../models';
// @ts-ignore
import type { PaperChatRequest } from '../models';
// @ts-ignore
import type { PaperChatResponse } from '../models';
/**
 * PaperChatApi - axios parameter creator
 */
export const PaperChatApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Allows the user to ask questions about the paper currently being viewed. Context is derived from the full PDF text and optional chat history.
         * @summary Chat with the specified paper
         * @param {number} paperId 
         * @param {PaperChatRequest} paperChatRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        chatWithPaperPapersPaperIdChatPost: async (paperId: number, paperChatRequest: PaperChatRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'paperId' is not null or undefined
            assertParamExists('chatWithPaperPapersPaperIdChatPost', 'paperId', paperId)
            // verify required parameter 'paperChatRequest' is not null or undefined
            assertParamExists('chatWithPaperPapersPaperIdChatPost', 'paperChatRequest', paperChatRequest)
            const localVarPath = `/papers/{paper_id}/chat`
                .replace(`{${"paper_id"}}`, encodeURIComponent(String(paperId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(paperChatRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PaperChatApi - functional programming interface
 */
export const PaperChatApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PaperChatApiAxiosParamCreator(configuration)
    return {
        /**
         * Allows the user to ask questions about the paper currently being viewed. Context is derived from the full PDF text and optional chat history.
         * @summary Chat with the specified paper
         * @param {number} paperId 
         * @param {PaperChatRequest} paperChatRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async chatWithPaperPapersPaperIdChatPost(paperId: number, paperChatRequest: PaperChatRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaperChatResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.chatWithPaperPapersPaperIdChatPost(paperId, paperChatRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PaperChatApi.chatWithPaperPapersPaperIdChatPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PaperChatApi - factory interface
 */
export const PaperChatApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PaperChatApiFp(configuration)
    return {
        /**
         * Allows the user to ask questions about the paper currently being viewed. Context is derived from the full PDF text and optional chat history.
         * @summary Chat with the specified paper
         * @param {number} paperId 
         * @param {PaperChatRequest} paperChatRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        chatWithPaperPapersPaperIdChatPost(paperId: number, paperChatRequest: PaperChatRequest, options?: RawAxiosRequestConfig): AxiosPromise<PaperChatResponse> {
            return localVarFp.chatWithPaperPapersPaperIdChatPost(paperId, paperChatRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PaperChatApi - object-oriented interface
 */
export class PaperChatApi extends BaseAPI {
    /**
     * Allows the user to ask questions about the paper currently being viewed. Context is derived from the full PDF text and optional chat history.
     * @summary Chat with the specified paper
     * @param {number} paperId 
     * @param {PaperChatRequest} paperChatRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public chatWithPaperPapersPaperIdChatPost(paperId: number, paperChatRequest: PaperChatRequest, options?: RawAxiosRequestConfig) {
        return PaperChatApiFp(this.configuration).chatWithPaperPapersPaperIdChatPost(paperId, paperChatRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

