/* tslint:disable */
/* eslint-disable */
/**
 * Inquiro API
 * AI-powered research discovery backend for Inquiro.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { HTTPValidationError } from '../models';
// @ts-ignore
import type { ProjectCreate } from '../models';
// @ts-ignore
import type { ProjectResponse } from '../models';
// @ts-ignore
import type { ProjectUpdate } from '../models';
// @ts-ignore
import type { ProjectWithPapersResponse } from '../models';
/**
 * ProjectsApi - axios parameter creator
 */
export const ProjectsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Store a reference to an existing paper in the given project.
         * @summary Add a paper to a project
         * @param {number} projectId 
         * @param {number} paperId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addPaperToProjectProjectsProjectIdPapersPaperIdPost: async (projectId: number, paperId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'projectId' is not null or undefined
            assertParamExists('addPaperToProjectProjectsProjectIdPapersPaperIdPost', 'projectId', projectId)
            // verify required parameter 'paperId' is not null or undefined
            assertParamExists('addPaperToProjectProjectsProjectIdPapersPaperIdPost', 'paperId', paperId)
            const localVarPath = `/projects/{project_id}/papers/{paper_id}`
                .replace(`{${"project_id"}}`, encodeURIComponent(String(projectId)))
                .replace(`{${"paper_id"}}`, encodeURIComponent(String(paperId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Create a new project for the authenticated user.
         * @summary Create a new project
         * @param {ProjectCreate} projectCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createProjectProjectsPost: async (projectCreate: ProjectCreate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'projectCreate' is not null or undefined
            assertParamExists('createProjectProjectsPost', 'projectCreate', projectCreate)
            const localVarPath = `/projects`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(projectCreate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete a project and its stored paper links.
         * @summary Delete a project
         * @param {number} projectId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteProjectProjectsProjectIdDelete: async (projectId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'projectId' is not null or undefined
            assertParamExists('deleteProjectProjectsProjectIdDelete', 'projectId', projectId)
            const localVarPath = `/projects/{project_id}`
                .replace(`{${"project_id"}}`, encodeURIComponent(String(projectId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Return a single project and all papers stored in it.
         * @summary Get a project with its stored papers
         * @param {number} projectId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectProjectsProjectIdGet: async (projectId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'projectId' is not null or undefined
            assertParamExists('getProjectProjectsProjectIdGet', 'projectId', projectId)
            const localVarPath = `/projects/{project_id}`
                .replace(`{${"project_id"}}`, encodeURIComponent(String(projectId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Return all projects for the authenticated user.
         * @summary List projects of the current user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listProjectsProjectsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/projects`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Remove a stored paper reference from the given project.
         * @summary Remove a paper from a project
         * @param {number} projectId 
         * @param {number} paperId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removePaperFromProjectProjectsProjectIdPapersPaperIdDelete: async (projectId: number, paperId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'projectId' is not null or undefined
            assertParamExists('removePaperFromProjectProjectsProjectIdPapersPaperIdDelete', 'projectId', projectId)
            // verify required parameter 'paperId' is not null or undefined
            assertParamExists('removePaperFromProjectProjectsProjectIdPapersPaperIdDelete', 'paperId', paperId)
            const localVarPath = `/projects/{project_id}/papers/{paper_id}`
                .replace(`{${"project_id"}}`, encodeURIComponent(String(projectId)))
                .replace(`{${"paper_id"}}`, encodeURIComponent(String(paperId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update the metadata of a project (e.g., name).
         * @summary Update a project
         * @param {number} projectId 
         * @param {ProjectUpdate} projectUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateProjectProjectsProjectIdPatch: async (projectId: number, projectUpdate: ProjectUpdate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'projectId' is not null or undefined
            assertParamExists('updateProjectProjectsProjectIdPatch', 'projectId', projectId)
            // verify required parameter 'projectUpdate' is not null or undefined
            assertParamExists('updateProjectProjectsProjectIdPatch', 'projectUpdate', projectUpdate)
            const localVarPath = `/projects/{project_id}`
                .replace(`{${"project_id"}}`, encodeURIComponent(String(projectId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(projectUpdate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProjectsApi - functional programming interface
 */
export const ProjectsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ProjectsApiAxiosParamCreator(configuration)
    return {
        /**
         * Store a reference to an existing paper in the given project.
         * @summary Add a paper to a project
         * @param {number} projectId 
         * @param {number} paperId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addPaperToProjectProjectsProjectIdPapersPaperIdPost(projectId: number, paperId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProjectWithPapersResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addPaperToProjectProjectsProjectIdPapersPaperIdPost(projectId, paperId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectsApi.addPaperToProjectProjectsProjectIdPapersPaperIdPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Create a new project for the authenticated user.
         * @summary Create a new project
         * @param {ProjectCreate} projectCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createProjectProjectsPost(projectCreate: ProjectCreate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProjectResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createProjectProjectsPost(projectCreate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectsApi.createProjectProjectsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Delete a project and its stored paper links.
         * @summary Delete a project
         * @param {number} projectId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteProjectProjectsProjectIdDelete(projectId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteProjectProjectsProjectIdDelete(projectId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectsApi.deleteProjectProjectsProjectIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Return a single project and all papers stored in it.
         * @summary Get a project with its stored papers
         * @param {number} projectId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProjectProjectsProjectIdGet(projectId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProjectWithPapersResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getProjectProjectsProjectIdGet(projectId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectsApi.getProjectProjectsProjectIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Return all projects for the authenticated user.
         * @summary List projects of the current user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listProjectsProjectsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ProjectResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listProjectsProjectsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectsApi.listProjectsProjectsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Remove a stored paper reference from the given project.
         * @summary Remove a paper from a project
         * @param {number} projectId 
         * @param {number} paperId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async removePaperFromProjectProjectsProjectIdPapersPaperIdDelete(projectId: number, paperId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProjectWithPapersResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.removePaperFromProjectProjectsProjectIdPapersPaperIdDelete(projectId, paperId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectsApi.removePaperFromProjectProjectsProjectIdPapersPaperIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Update the metadata of a project (e.g., name).
         * @summary Update a project
         * @param {number} projectId 
         * @param {ProjectUpdate} projectUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateProjectProjectsProjectIdPatch(projectId: number, projectUpdate: ProjectUpdate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProjectResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateProjectProjectsProjectIdPatch(projectId, projectUpdate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectsApi.updateProjectProjectsProjectIdPatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ProjectsApi - factory interface
 */
export const ProjectsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ProjectsApiFp(configuration)
    return {
        /**
         * Store a reference to an existing paper in the given project.
         * @summary Add a paper to a project
         * @param {number} projectId 
         * @param {number} paperId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addPaperToProjectProjectsProjectIdPapersPaperIdPost(projectId: number, paperId: number, options?: RawAxiosRequestConfig): AxiosPromise<ProjectWithPapersResponse> {
            return localVarFp.addPaperToProjectProjectsProjectIdPapersPaperIdPost(projectId, paperId, options).then((request) => request(axios, basePath));
        },
        /**
         * Create a new project for the authenticated user.
         * @summary Create a new project
         * @param {ProjectCreate} projectCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createProjectProjectsPost(projectCreate: ProjectCreate, options?: RawAxiosRequestConfig): AxiosPromise<ProjectResponse> {
            return localVarFp.createProjectProjectsPost(projectCreate, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete a project and its stored paper links.
         * @summary Delete a project
         * @param {number} projectId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteProjectProjectsProjectIdDelete(projectId: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteProjectProjectsProjectIdDelete(projectId, options).then((request) => request(axios, basePath));
        },
        /**
         * Return a single project and all papers stored in it.
         * @summary Get a project with its stored papers
         * @param {number} projectId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectProjectsProjectIdGet(projectId: number, options?: RawAxiosRequestConfig): AxiosPromise<ProjectWithPapersResponse> {
            return localVarFp.getProjectProjectsProjectIdGet(projectId, options).then((request) => request(axios, basePath));
        },
        /**
         * Return all projects for the authenticated user.
         * @summary List projects of the current user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listProjectsProjectsGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<ProjectResponse>> {
            return localVarFp.listProjectsProjectsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Remove a stored paper reference from the given project.
         * @summary Remove a paper from a project
         * @param {number} projectId 
         * @param {number} paperId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removePaperFromProjectProjectsProjectIdPapersPaperIdDelete(projectId: number, paperId: number, options?: RawAxiosRequestConfig): AxiosPromise<ProjectWithPapersResponse> {
            return localVarFp.removePaperFromProjectProjectsProjectIdPapersPaperIdDelete(projectId, paperId, options).then((request) => request(axios, basePath));
        },
        /**
         * Update the metadata of a project (e.g., name).
         * @summary Update a project
         * @param {number} projectId 
         * @param {ProjectUpdate} projectUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateProjectProjectsProjectIdPatch(projectId: number, projectUpdate: ProjectUpdate, options?: RawAxiosRequestConfig): AxiosPromise<ProjectResponse> {
            return localVarFp.updateProjectProjectsProjectIdPatch(projectId, projectUpdate, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ProjectsApi - object-oriented interface
 */
export class ProjectsApi extends BaseAPI {
    /**
     * Store a reference to an existing paper in the given project.
     * @summary Add a paper to a project
     * @param {number} projectId 
     * @param {number} paperId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public addPaperToProjectProjectsProjectIdPapersPaperIdPost(projectId: number, paperId: number, options?: RawAxiosRequestConfig) {
        return ProjectsApiFp(this.configuration).addPaperToProjectProjectsProjectIdPapersPaperIdPost(projectId, paperId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Create a new project for the authenticated user.
     * @summary Create a new project
     * @param {ProjectCreate} projectCreate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createProjectProjectsPost(projectCreate: ProjectCreate, options?: RawAxiosRequestConfig) {
        return ProjectsApiFp(this.configuration).createProjectProjectsPost(projectCreate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Delete a project and its stored paper links.
     * @summary Delete a project
     * @param {number} projectId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteProjectProjectsProjectIdDelete(projectId: number, options?: RawAxiosRequestConfig) {
        return ProjectsApiFp(this.configuration).deleteProjectProjectsProjectIdDelete(projectId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Return a single project and all papers stored in it.
     * @summary Get a project with its stored papers
     * @param {number} projectId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getProjectProjectsProjectIdGet(projectId: number, options?: RawAxiosRequestConfig) {
        return ProjectsApiFp(this.configuration).getProjectProjectsProjectIdGet(projectId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Return all projects for the authenticated user.
     * @summary List projects of the current user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listProjectsProjectsGet(options?: RawAxiosRequestConfig) {
        return ProjectsApiFp(this.configuration).listProjectsProjectsGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Remove a stored paper reference from the given project.
     * @summary Remove a paper from a project
     * @param {number} projectId 
     * @param {number} paperId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public removePaperFromProjectProjectsProjectIdPapersPaperIdDelete(projectId: number, paperId: number, options?: RawAxiosRequestConfig) {
        return ProjectsApiFp(this.configuration).removePaperFromProjectProjectsProjectIdPapersPaperIdDelete(projectId, paperId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update the metadata of a project (e.g., name).
     * @summary Update a project
     * @param {number} projectId 
     * @param {ProjectUpdate} projectUpdate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateProjectProjectsProjectIdPatch(projectId: number, projectUpdate: ProjectUpdate, options?: RawAxiosRequestConfig) {
        return ProjectsApiFp(this.configuration).updateProjectProjectsProjectIdPatch(projectId, projectUpdate, options).then((request) => request(this.axios, this.basePath));
    }
}

