/* tslint:disable */
/* eslint-disable */
/**
 * Inquiro API
 * AI-powered research discovery backend for Inquiro.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ConditionGroupChildrenInner } from './condition-group-children-inner';

/**
 * Logical group combining multiple conditions with AND / OR.
 */
export interface ConditionGroup {
    'type': ConditionGroupTypeEnum;
    'operator': ConditionGroupOperatorEnum;
    'children': Array<ConditionGroupChildrenInner>;
}

export const ConditionGroupTypeEnum = {
    Group: 'group'
} as const;

export type ConditionGroupTypeEnum = typeof ConditionGroupTypeEnum[keyof typeof ConditionGroupTypeEnum];
export const ConditionGroupOperatorEnum = {
    And: 'AND',
    Or: 'OR'
} as const;

export type ConditionGroupOperatorEnum = typeof ConditionGroupOperatorEnum[keyof typeof ConditionGroupOperatorEnum];


