/* tslint:disable */
/* eslint-disable */
/**
 * Inquiro API
 * AI-powered research discovery backend for Inquiro.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UserResponse } from './user-response';

/**
 * Response returned after a successful login.
 */
export interface LoginResponse {
    'access_token': string;
    'refresh_token': string;
    'token_type': string;
    'user': UserResponse;
}

