/* tslint:disable */
/* eslint-disable */
/**
 * Inquiro API
 * AI-powered research discovery backend for Inquiro.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Structured response to summary request. Fields contain Markdown + LaTeX strings.
 */
export interface PaperSummaryResponse {
    /**
     * The title of the paper.
     */
    'title': string;
    /**
     * A high-level, 2-3 sentence overview of the paper\'s core contribution.
     */
    'executive_summary': string;
    'relevance_to_query'?: string | null;
    /**
     * List of technical steps/architectures (bullet points).
     */
    'methodology_points': Array<string>;
    /**
     * List of quantitative findings or theoretical results (bullet points).
     */
    'results_points': Array<string>;
    /**
     * Critical analysis of constraints or assumptions.
     */
    'limitations'?: string;
}

