/* tslint:disable */
/* eslint-disable */
/**
 * Inquiro API
 * AI-powered research discovery backend for Inquiro.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The AI generated response for the chat. Supports Markdown and LaTeX.
 */
export interface PaperChatResponse {
    /**
     * The AI\'s response to the user\'s question.
     */
    'answer': string;
}

