/* tslint:disable */
/* eslint-disable */
/**
 * Inquiro API
 * AI-powered research discovery backend for Inquiro.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Lightweight representation of a paper inside a project.
 */
export interface PaperSummary {
    'paper_id': number;
    'title': string;
    'authors'?: { [key: string]: any; } | null;
    'abstract'?: string | null;
    'published_at'?: string | null;
    'url'?: string | null;
    'pdf_url'?: string | null;
}

