/* tslint:disable */
/* eslint-disable */
/**
 * Inquiro API
 * AI-powered research discovery backend for Inquiro.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Representation of a paper (as specified in the DB)
 */
export interface Paper {
    'paper_id': number;
    'doi': string;
    'source': string;
    'paper_type': string;
    'title': string;
    'authors': { [key: string]: string; } | null;
    'abstract': string | null;
    'published_at': string | null;
    'pdf_url': string | null;
    'url': string | null;
    'fetched_at': string;
}

