/* tslint:disable */
/* eslint-disable */
/**
 * Inquiro API
 * AI-powered research discovery backend for Inquiro.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PaperDto } from './paper-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { ProjectResponse } from './project-response';

/**
 * Project including its stored papers.
 */
export interface ProjectWithPapersResponse {
    'project': ProjectResponse;
    'papers': Array<PaperDto>;
}

