/* tslint:disable */
/* eslint-disable */
/**
 * Inquiro API
 * AI-powered research discovery backend for Inquiro.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Paper } from './paper';

/**
 * Response to search for specified query
 */
export interface SearchResponse {
    'papers': Array<Paper>;
}

