/* tslint:disable */
/* eslint-disable */
/**
 * Inquiro API
 * AI-powered research discovery backend for Inquiro.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface TextCondition {
    'type': TextConditionTypeEnum;
    'field': TextConditionFieldEnum;
    'operator': TextConditionOperatorEnum;
    'value': string;
}

export const TextConditionTypeEnum = {
    Condition: 'condition'
} as const;

export type TextConditionTypeEnum = typeof TextConditionTypeEnum[keyof typeof TextConditionTypeEnum];
export const TextConditionFieldEnum = {
    Title: 'title',
    Abstract: 'abstract'
} as const;

export type TextConditionFieldEnum = typeof TextConditionFieldEnum[keyof typeof TextConditionFieldEnum];
export const TextConditionOperatorEnum = {
    Contains: 'contains',
    NotContains: 'not_contains'
} as const;

export type TextConditionOperatorEnum = typeof TextConditionOperatorEnum[keyof typeof TextConditionOperatorEnum];


